apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    app: redis-sentinel
spec:
  selector:
    app: redis-sentinel
  clusterIP: None
  ports:
  - port: {{ .Values.sentinel.port }}
    name: redis-sentinel