FROM redis:5
COPY cluster/create-cluster create-cluster
COPY cluster/create-cluster-node create-cluster-node
COPY sentinel/sentinel-conf-local sentinel-conf-local
COPY sentinel/sentinel-conf-test sentinel-conf-test
COPY sentinel/sentinel-conf-201 sentinel-conf-201
COPY sentinel/sentinel-conf-55 sentinel-conf-55
COPY sentinel/redis-node-conf redis-node-conf
COPY sentinel/sentinel-conf-local-5n sentinel-conf-local-5n