apiVersion: v1
kind: Secret
metadata:
  name: logging-pki-client
  namespace: {{ .Values.global.namespace }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
data:
  ca-kafka-cert.pem: "{{ .Values.fluenbit_journal_secret.ca_kafka_cert }}"
  client-kafka-cert.pem: "{{ .Values.fluenbit_journal_secret.client_kafka_cert }}"
  client-kafka-cert-key.pem: "{{ .Values.fluenbit_journal_secret.client_kafka_cert_key }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: logging-pki-pass-client
  namespace: {{ .Values.global.namespace }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
stringData:
  client-kafka-cert-key-password: {{ .Values.fluenbit_journal_secret.client_kafka_cert_key_password }}